# Generated by Django 5.2.1 on 2025-06-01 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_address_user_address2_user_cities_user_postal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='province',
        ),
    ]
