# Generated by Django 5.2.1 on 2025-07-03 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_user_address2_remove_user_province'),
        ('product', '0005_alter_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='color',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='grid',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='product',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='quantity',
        ),
        migrations.CreateModel(
            name='BasketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.basket')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.color')),
                ('grid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.grid')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
