# Generated by Django 5.2.1 on 2025-11-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_basket_color_remove_basket_grid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
