# Generated by Django 5.2.1 on 2025-11-26 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_basketitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketitem',
            name='price',
        ),
    ]
