# Generated by Django 5.2.1 on 2025-11-26 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_basketitem_price'),
        ('product', '0006_product_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='basketitem',
            name='update_at',
        ),
        migrations.AddField(
            model_name='basketitem',
            name='custom_height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basketitem',
            name='custom_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basketitem',
            name='custom_width',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.color'),
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='grid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.grid'),
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
