# Generated by Django 5.2.1 on 2025-06-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Grid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('GLASS', 'GLASS'), ('MDF', 'MDF')], max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='PosterIMGs/')),
                ('price', models.FloatField()),
                ('slug', models.SlugField(unique=True)),
                ('color', models.ManyToManyField(blank=-1, to='product.color')),
                ('grid', models.ManyToManyField(blank=True, to='product.grid')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
