# Generated by Django 5.2.1 on 2025-06-22 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_color_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('FOR KIDS', 'FOR KIDS'), ('FOR ANIMAL', 'FOR ANIMAL')], max_length=50),
        ),
    ]
