# Generated by Django 5.2.1 on 2025-07-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detail',
            field=models.CharField(default=1, max_length=55),
            preserve_default=False,
        ),
    ]
